#
# This file contains configuration flags to customize your site
#

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "routes"
      type: "routes"
    values:
      layout: "route"
#      permalink: "/:title"
  -
    scope:
      path: ""
      type: "features"
    values:
      layout: "feature"

collections:
  features:
    output: true
  routes:
    output: true

apikeys:
    bing: Ar0NqGYN0lECfmYJcKI0JQPmv2gZ_ISK-0y-ti9Wz1jOjtv7hZD3nqLV9j3an-Hi
    mapbox: pk.eyJ1IjoicHdyIiwiYSI6Il91MVVLWTQifQ.1YZ2WV0YGPCd2H9PIODhBA

kramdown:
  input: GFM

# plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
